package org.sample.unreliable.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-02-15T15:21:36.789-06:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "greeting", 
                  wsdlLocation = "file:/home/rick/workspace/Fuse6.2.1/ExcHandle_CamelRoute/A_UnreliableWebService/WebContent/WEB-INF/wsdl/greeting.wsdl",
                  targetNamespace = "http://cxf.examples.camel.wildfly.org/") 
public class Greeting_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.examples.camel.wildfly.org/", "greeting");
    public final static QName GreetingServiceImplPort = new QName("http://cxf.examples.camel.wildfly.org/", "GreetingServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/rick/workspace/Fuse6.2.1/ExcHandle_CamelRoute/A_UnreliableWebService/WebContent/WEB-INF/wsdl/greeting.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Greeting_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/rick/workspace/Fuse6.2.1/ExcHandle_CamelRoute/A_UnreliableWebService/WebContent/WEB-INF/wsdl/greeting.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Greeting_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Greeting_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Greeting_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Greeting_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Greeting_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Greeting_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingServiceImplPort")
    public Greeting getGreetingServiceImplPort() {
        return super.getPort(GreetingServiceImplPort, Greeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingServiceImplPort")
    public Greeting getGreetingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GreetingServiceImplPort, Greeting.class, features);
    }

}
