
package org.sample;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * 2018-11-07T13:33:32.300-06:00
 * Generated source version: 3.1.12.redhat-1
 */

@WebFault(name = "fault", targetNamespace = "http://ws.sample.org/payment-service/types")
public class FaultMessage extends Exception {
    
    private org.sample.Fault fault;

    public FaultMessage() {
        super();
    }
    
    public FaultMessage(String message) {
        super(message);
    }
    
    public FaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, org.sample.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMessage(String message, org.sample.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.sample.Fault getFaultInfo() {
        return this.fault;
    }
}
