package org.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * 2018-11-07T13:33:32.317-06:00
 * Generated source version: 3.1.12.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.sample.org/payment-service", name = "Payment")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Payment {

    @WebMethod
    @WebResult(name = "transferResponse", targetNamespace = "http://ws.sample.org/payment-service/types", partName = "response")
    public TransferResponse transferFunds(
        @WebParam(partName = "payload", name = "transferRequest", targetNamespace = "http://ws.sample.org/payment-service/types")
        TransferRequest payload
    ) throws FaultMessage;
}
